spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/websport
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: 8080

jwt:
  secret: "websport_secret_key_chuoi_nay_phai_that_la_dai_va_bao_mat_nhe_1234567890_abcdef"
  expiration: 604800000
