spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/websport
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

# --- CLOUDINARY CONFIG ---
cloudinary:
  cloud-name: Root
  api-key: 441211244436394
  api-secret: mHV8O459rPrEVp4O1YXdl9xu4II